apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ratings
    version: v1
  name: ratings-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        kiali.io/runtimes: nodejs
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - image: jotak/bookinfo-runtimes-ratings-v1:latest
        imagePullPolicy: IfNotPresent
        name: ratings-v1
        ports:
        - containerPort: 9080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
